name: Import blocklists

on:
  push:
    paths:
      - 'sources/imports/**.txt'
  schedule:
    - cron:  '42 3,15 * * *'
  workflow_dispatch:

jobs:
  import:
    name: Import blocklists

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"
    - name: Run import
      run: ./scripts/import.sh
    - name: Run update
      run: ./scripts/update.sh
    - name: Commit and push
      run: |
        git config --local user.email "154800279+cnn2345@users.noreply.github.com"
        git config --local user.name "cnn2345"
        git add -A
        if git commit -m "Import blocklists"; then
          git push
        fi
